import type { Metadata } from "next";
import { Inter, Lato, Urbanist, Titillium_Web, Amaranth } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./components/Common/theme-provider";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "./api/uploadthing/core";
import NextTopLoader from 'nextjs-toploader';
import { cn } from "@/lib/utils";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });
const lato = Lato({ weight: "400", subsets: ["latin"] });
const urbanist = Urbanist({ weight: "400", subsets: ["latin"] });
const titillium_Web = Titillium_Web({ weight: "400", subsets: ["latin"] });
export const amaranth = Amaranth({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(titillium_Web.className, "bg-none")}>
        <NextSSRPlugin
          routerConfig={extractRouterConfig(ourFileRouter)}
        />
        <NextTopLoader />
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <div>
            {children}
          </div>
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
